"""create annotator stats table

Revision ID: 414c3f11db90
Revises: 
Create Date: 2025-06-22 19:17:47.787653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '414c3f11db90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotatorstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('files_read', sa.Integer(), nullable=False),
    sa.Column('remaining_texts', sa.Integer(), nullable=False),
    sa.Column('minutes_recorded', sa.Float(), nullable=False),
    sa.Column('has_started', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotatorstat_annotator_id'), 'annotatorstat', ['annotator_id'], unique=False)
    op.create_index(op.f('ix_annotatorstat_language'), 'annotatorstat', ['language'], unique=False)
    op.create_index(op.f('ix_annotatorstat_report_date'), 'annotatorstat', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotatorstat_report_date'), table_name='annotatorstat')
    op.drop_index(op.f('ix_annotatorstat_language'), table_name='annotatorstat')
    op.drop_index(op.f('ix_annotatorstat_annotator_id'), table_name='annotatorstat')
    op.drop_table('annotatorstat')
    # ### end Alembic commands ###
